export const attractions = [
    { name: "Roads & Infrastructure", value: "roads_infrastructure" },
    { name: "Hotels & Resorts", value: "hotels_resorts" },
    { name: "Gyms & Fitness Centers", value: "gyms_fitness_centers" },
    { name: "Restaurants & Cafés", value: "restaurants_cafes" },
    { name: "National Parks & Wildlife Reserves", value: "national_parks_wildlife_reserves" },
    { name: "Cultural & Historical Sites", value: "cultural_historical_sites" },
    { name: "Shopping Malls & Markets", value: "shopping_malls_markets" },
    { name: "Beaches & Lakes", value: "beaches_lakes" },
    { name: "Tourist Attractions", value: "tourist_attractions" },
    { name: "Museums & Art Galleries", value: "museums_art_galleries" },
    { name: "Spas & Wellness Centers", value: "spas_wellness_centers" },
    { name: "Nightlife & Entertainment Venues", value: "nightlife_entertainment" },
    { name: "Event Spaces & Convention Centers", value: "event_spaces_convention_centers" },
    { name: "Adventure & Outdoor Activities)", value: "adventure_outdoor_activities" },
    { name: "Educational Institutions & Universities", value: "educational_institutions_universities" },
    { name: "Sports Arenas & Stadiums", value: "sports_arenas_stadiums" },
    { name: "Religious Sites", value: "religious_sites" },
    { name: "Public Parks & Gardens", value: "public_parks_gardens" },
    { name: "Transportation Services", value: "transportation_services" },
    { name: "Technology & Innovation Hubs", value: "technology_innovation_hubs" }
];

export const eventsInRwanda = [
    { name: "Kigali International Peace Marathon", value: "kigali_international_peace_marathon" },
    { name: "Kigali Fashion Week", value: "kigali_fashion_week" },
    { name: "Kwita Izina (Gorilla Naming Ceremony)", value: "kwita_izina" },
    { name: "Tour du Rwanda (Cycling Race)", value: "tour_du_rwanda" },
    { name: "Ubumuntu Arts Festival", value: "ubumuntu_arts_festival" },
    { name: "Rwanda Film Festival", value: "rwanda_film_festival" },
    { name: "Rwanda Cultural Day", value: "rwanda_cultural_day" },
    { name: "Rwanda International Trade Fair", value: "rwanda_international_trade_fair" },
    { name: "YouthConnekt Africa Summit", value: "youthconnekt_africa_summit" },
    { name: "KigaliUp Music Festival", value: "kigaliup_music_festival" },
    { name: "Africa CEO Forum", value: "africa_ceo_forum" },
    { name: "CHOGM (Commonwealth Heads of Government Meeting)", value: "chogm" },
    { name: "FESPAD (Pan-African Dance Festival)", value: "fespad" },
    { name: "International Conference on Family Planning", value: "international_conference_family_planning" },
    { name: "East African Military Games", value: "east_african_military_games" },
    { name: "Miss Rwanda Beauty Pageant", value: "miss_rwanda_beauty_pageant" },
    { name: "Rwanda Day", value: "rwanda_day" },
    { name: "Kigali Global Dialogue", value: "kigali_global_dialogue" },
    { name: "Africa Green Revolution Forum", value: "africa_green_revolution_forum" },
    { name: "Made in Rwanda Expo", value: "made_in_rwanda_expo" }
];

export const postToCreateTypes = [
    { name: "Province", value: "province" },
    { name: "District", value: "district" },
    { name: "Economic Activity", value: "economic_activity" },
    { name: "Event", value: "event" },
];

export const districts = [
    { name: "Nyarugenge", id: "1" },
    { name: "Gasabo", id: "2" },
    { name: "Kicukiro", id: "3" },
    { name: "Rulindo", id: "4" },
    { name: "Gicumbi", id: "5" },
    { name: "Burera", id: "6" },
    { name: "Musanze", id: "7" },
    { name: "Gakenke", id: "8" },
    { name: "Kamonyi", id: "9" },
    { name: "Ruhango", id: "10" },
    { name: "Muhanga", id: "11" },
    { name: "Nyanza", id: "12" },
    { name: "Huye", id: "13" },
    { name: "Gisagara", id: "14" },
    { name: "Nyamagabe", id: "15" },
    { name: "Nyaruguru", id: "16" },
    { name: "Rusizi", id: "17" },
    { name: "Nyamasheke", id: "18" },
    { name: "Karongi", id: "19" },
    { name: "Rutsiro", id: "20" },
    { name: "Rubavu", id: "21" },
    { name: "Ngororero", id: "22" },
    { name: "Nyabihu", id: "23" },
    { name: "Rwamagana", id: "24" },
    { name: "Kayonza", id: "25" },
    { name: "Kirehe", id: "26" },
    { name: "Ngoma", id: "27" },
    { name: "Bugesera", id: "28" },
    { name: "Gatsibo", id: "29" },
    { name: "Nyagatare", id: "30" }
];
