import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "@uploadthing/react/styles.css";

import { Toaster } from "react-hot-toast";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { StateContext } from "@/context/stateContext";
import { AuthProvider } from "@/components/providers/sessionproviders";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <StateContext>
            <GoogleOAuthProvider clientId={process.env.CLIENT_ID as string}>
              {children}
              <Toaster />
            </GoogleOAuthProvider>
          </StateContext>
        </AuthProvider>
      </body>
    </html>
  );
}
